AllCops:
  Exclude:
    - gems/**/*
    - init_templates/**/*
    - lib/measures/**/resources/*
    - lib/openstudio/extension/core/**/*
  TargetRubyVersion: 3.2.2

require: rubocop-performance
inherit_from:
  - http://s3.amazonaws.com/openstudio-resources/styles/rubocop_v4.yml
